@startuml

class Project extends Node{
    -children : ArrayList<Node>
    +acceptVisitor(visitor : Visitor)
    +updateTree(period : Long, endTime : LocalDateTime)
}

abstract class Node {
    -name : string
    -startTime : LocalDateTime
    -endTime : LocalDateTime
    -totalWorkingTime : Duration
    +{abstract} acceptVisitor(visitor : Visitor)
    +{abstract} updateTree(period : Long, endTime : LocalDateTime)
}

class Task extends Node{
    -timeIntervals : List<TimeInterval>
    -lastAdded : TimeInterval
    +startTask()
    +stopTask()
    +acceptVisitor(visit : Visitor)
    +updateTree(period : Long, endTime : LocalDateTime)
}

class Client {
+ {static}main(args : String[])
}

class TimeInterval {
    -task : Task
    -startTime : LocalDateTime
    -endTime : LocalDateTime
    -totalWorkingTime : Duration
    +update(o : Observable, arg : Object)
    +acceptVisitor(visit : Visitor)
}
package java.util <<Folder>> {
    interface Observer{
        +update(arg0 : Observable,
        arg1 : Object)
    }
    abstract class Observable{
        +addObserver (ob: Observer)
        +deleteObserver (ob: Observer)
        +setChanged()
        +notifyObservers(arg0: Observable, arg1: Object)
    }
}

class Clock{
    -timerTask : Duration
    -timer : Timer
    -{static}period : long
    -{static}uniqueInstance : Clock
    -stopClock : boolean
    +stopClock()
    -tick()
    +getInstance() : Clock
}

interface Visitor {
    +visitTask(t : Task)
    +visitProject(p : Project)
    +visitTimeInterval(interval : TimeInterval)
}
class TreePrinter implements Visitor{
     -root : Project
     -formatter : DateTimeFormatter
     +visitTask(t : Task)
     +visitProject(p : Project)
     +visitTimeInterval(interval : TimeInterval)
     +update(o : Observable, arg : Object)
}
Visitor -[hidden]right- Observable
Node <--* Project : "*" nodes
TimeInterval "*"<--*  Task : timeintervals
TimeInterval ..|> Observer
Observer <--o Observable : "*"observers
Observable <|-- Clock
Client  o-->"*" Node

@enduml
